### ISSUE TITLE
Pods are not running properly

### ISSUE THREAD

**Issue by Yacine8888** [CENGN/netbox-kubernetes#1]
Hi,
I'm trying to deploy netbox with k8s using your sources.
And so far it doesn't work, the pods are not in running state:
NAME                            READY   STATUS              RESTARTS   AGE
netbox-685698f884-nkk9x         1/2     Running             0          14s
netbox-685698f884-sf9ng         1/2     CrashLoopBackOff    12         64m
netbox-68c6749859-rdcq5         0/2     ContainerCreating   0          61m
netbox-68c6749859-zhrl6         0/2     ContainerCreating   0          14s
netbox-community-postgresql-0   0/1     Pending             0          12d
netbox-redis-master-0           0/2     Pending             0          12d
netbox-redis-slave-0            0/2     Pending             0          12d

I am still learning kubernetes so I am not an expert.
I put a log file pod.txt.
If you can help me please.

[pod.txt](https://github.com/CENGN/netbox-kubernetes/files/4749331/pod.txt)

**Comment by mohahmed13** [comment]
Hi @Yacine8888 , this is likely because you're not replacing the storage class with your own storage class. See the note under step 2: storageClass should reflect the appropriate storage class for the environment. 

In this example, we're using Rook-Ceph, a storage provider for K8s leveraging the Rook operator to deploy a Ceph cluster. Visit https://rook.io/ for more information.

**Comment by mohahmed13** [comment]
Please reach out if you have any further questions!
